version: '3'

services:
  izing-redis:
    container_name: "izing-redis"
    image: 'redis:latest'
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    volumes:
      - '/var/izing/redis:/data'
    networks:
      - izing_db_network

  izing-rabbitmq:
    image: rabbitmq:3-management
    hostname: izing-rabbit
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      # - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      # - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      # - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - /var/izing/rabbitmq/data/:/var/lib/rabbitmq/
      - /var/izing/rabbitmq/logs/:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - izing_db_network

networks:
  izing_network:
    driver: bridge
  izing_db_network:
    driver: bridge
